# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  stripe:
    publishable_key: pk_test_IzhuYTLpq59SqGFxyvm5uZ6c
    secret_key: sk_test_Hg4OEUwBzyDjzt8kkdzxjQjN
    webhook_secret: 68f622dbdcbd81ed6f681d447682de3d72cdb1cb204d642b25b358d23162a8bf67b97e4625f2f813038f728ad79b379e8302cf757b637e6d5d40f6bc4ec39c23
  secret_key_base: 15d9c20e968308345e498f69fb650e0f8267e32a281ef44d14ab7d7581a6e64de2b850bc4ab617ac56ed0ba45e9b73a3e76ca48768dee58fd2b5c5ad09905ced

test:
  stripe:
    publishable_key: pk_test_IzhuYTLpq59SqGFxyvm5uZ6c
    secret_key: sk_test_Hg4OEUwBzyDjzt8kkdzxjQjN
    webhook_secret: 68f622dbdcbd81ed6f681d447682de3d72cdb1cb204d642b25b358d23162a8bf67b97e4625f2f813038f728ad79b379e8302cf757b637e6d5d40f6bc4ec39c23
  secret_key_base: 753a551cdf2b01b1d8a9d24d8c77f18ba26f153fdc2b37bfbbdbbdb2b39f1eee4f2eb5655fbb0fab961800c56f86db9fb06f73721d6befb29cb7ee7c08e3bbab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  stripe:
    # publishable_key: pk_test_IzhuYTLpq59SqGFxyvm5uZ6c
    # secret_key: sk_test_Hg4OEUwBzyDjzt8kkdzxjQjN
    webhook_secret: 532baaad612fa2cf2a9725b2d53784deb1d704662b06e59a89393cd0feb22dc0978dbe259cca86d5da2b6bf01826f97b55796a2f78a49ab204b816563b28bded
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

